# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Sequential
version:      0.4.2
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
